# Generated by Django 5.0.6 on 2024-09-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_customer_card_number_customer_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
